name: BukkitForgeItemsLib
version: 0.0.0.0000
description: This plugin allows developers to add custom items with custom textures or models.
load: STARTUP
authors: [Saukiya, Hykilpikonna]
main: cc.moecraft.saukiya.bukkitforgeitemslib.Main
database: false
depend: []
softdepend: []
loadbefore: []
commands:
  bukkitforgeitemslib:
    description: The main command
    aliases: bfil
    permission: bfil.admin
    usage: Definately useful